package com.wjh.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class KhJld implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kh_jld.jldbh
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String jldbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kh_jld.gsdwbm
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String gsdwbm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kh_jld.jshh
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String jshh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kh_jld.yhbh
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String yhbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kh_jld.jlddz
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String jlddz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kh_jld.jldmc
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String jldmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kh_jld.jldcblx
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String jldcblx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kh_jld.jldlx
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String jldlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kh_jld.yslx
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String yslx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kh_jld.jldzt
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String jldzt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kh_jld.dqbm
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String dqbm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kh_jld.yysl
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private BigDecimal yysl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kh_jld.jldqyrq
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private Date jldqyrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kh_jld.cjsj
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private Date cjsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kh_jld.czsj
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private Date czsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kh_jld
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kh_jld.jldbh
     *
     * @return the value of kh_jld.jldbh
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getJldbh() {
        return jldbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kh_jld.jldbh
     *
     * @param jldbh the value for kh_jld.jldbh
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setJldbh(String jldbh) {
        this.jldbh = jldbh == null ? null : jldbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kh_jld.gsdwbm
     *
     * @return the value of kh_jld.gsdwbm
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getGsdwbm() {
        return gsdwbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kh_jld.gsdwbm
     *
     * @param gsdwbm the value for kh_jld.gsdwbm
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setGsdwbm(String gsdwbm) {
        this.gsdwbm = gsdwbm == null ? null : gsdwbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kh_jld.jshh
     *
     * @return the value of kh_jld.jshh
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getJshh() {
        return jshh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kh_jld.jshh
     *
     * @param jshh the value for kh_jld.jshh
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setJshh(String jshh) {
        this.jshh = jshh == null ? null : jshh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kh_jld.yhbh
     *
     * @return the value of kh_jld.yhbh
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getYhbh() {
        return yhbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kh_jld.yhbh
     *
     * @param yhbh the value for kh_jld.yhbh
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setYhbh(String yhbh) {
        this.yhbh = yhbh == null ? null : yhbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kh_jld.jlddz
     *
     * @return the value of kh_jld.jlddz
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getJlddz() {
        return jlddz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kh_jld.jlddz
     *
     * @param jlddz the value for kh_jld.jlddz
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setJlddz(String jlddz) {
        this.jlddz = jlddz == null ? null : jlddz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kh_jld.jldmc
     *
     * @return the value of kh_jld.jldmc
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getJldmc() {
        return jldmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kh_jld.jldmc
     *
     * @param jldmc the value for kh_jld.jldmc
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setJldmc(String jldmc) {
        this.jldmc = jldmc == null ? null : jldmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kh_jld.jldcblx
     *
     * @return the value of kh_jld.jldcblx
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getJldcblx() {
        return jldcblx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kh_jld.jldcblx
     *
     * @param jldcblx the value for kh_jld.jldcblx
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setJldcblx(String jldcblx) {
        this.jldcblx = jldcblx == null ? null : jldcblx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kh_jld.jldlx
     *
     * @return the value of kh_jld.jldlx
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getJldlx() {
        return jldlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kh_jld.jldlx
     *
     * @param jldlx the value for kh_jld.jldlx
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setJldlx(String jldlx) {
        this.jldlx = jldlx == null ? null : jldlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kh_jld.yslx
     *
     * @return the value of kh_jld.yslx
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getYslx() {
        return yslx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kh_jld.yslx
     *
     * @param yslx the value for kh_jld.yslx
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setYslx(String yslx) {
        this.yslx = yslx == null ? null : yslx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kh_jld.jldzt
     *
     * @return the value of kh_jld.jldzt
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getJldzt() {
        return jldzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kh_jld.jldzt
     *
     * @param jldzt the value for kh_jld.jldzt
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setJldzt(String jldzt) {
        this.jldzt = jldzt == null ? null : jldzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kh_jld.dqbm
     *
     * @return the value of kh_jld.dqbm
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getDqbm() {
        return dqbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kh_jld.dqbm
     *
     * @param dqbm the value for kh_jld.dqbm
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setDqbm(String dqbm) {
        this.dqbm = dqbm == null ? null : dqbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kh_jld.yysl
     *
     * @return the value of kh_jld.yysl
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public BigDecimal getYysl() {
        return yysl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kh_jld.yysl
     *
     * @param yysl the value for kh_jld.yysl
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setYysl(BigDecimal yysl) {
        this.yysl = yysl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kh_jld.jldqyrq
     *
     * @return the value of kh_jld.jldqyrq
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public Date getJldqyrq() {
        return jldqyrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kh_jld.jldqyrq
     *
     * @param jldqyrq the value for kh_jld.jldqyrq
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setJldqyrq(Date jldqyrq) {
        this.jldqyrq = jldqyrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kh_jld.cjsj
     *
     * @return the value of kh_jld.cjsj
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public Date getCjsj() {
        return cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kh_jld.cjsj
     *
     * @param cjsj the value for kh_jld.cjsj
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setCjsj(Date cjsj) {
        this.cjsj = cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kh_jld.czsj
     *
     * @return the value of kh_jld.czsj
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public Date getCzsj() {
        return czsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kh_jld.czsj
     *
     * @param czsj the value for kh_jld.czsj
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setCzsj(Date czsj) {
        this.czsj = czsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kh_jld
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", jldbh=").append(jldbh);
        sb.append(", gsdwbm=").append(gsdwbm);
        sb.append(", jshh=").append(jshh);
        sb.append(", yhbh=").append(yhbh);
        sb.append(", jlddz=").append(jlddz);
        sb.append(", jldmc=").append(jldmc);
        sb.append(", jldcblx=").append(jldcblx);
        sb.append(", jldlx=").append(jldlx);
        sb.append(", yslx=").append(yslx);
        sb.append(", jldzt=").append(jldzt);
        sb.append(", dqbm=").append(dqbm);
        sb.append(", yysl=").append(yysl);
        sb.append(", jldqyrq=").append(jldqyrq);
        sb.append(", cjsj=").append(cjsj);
        sb.append(", czsj=").append(czsj);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}