package com.wjh.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class KhJsh implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kh_jsh.JSHH
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String jshh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kh_jsh.GDDWBM
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String gddwbm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kh_jsh.KHBH
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String khbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kh_jsh.JSHMC
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String jshmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kh_jsh.JSHDZ
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String jshdz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kh_jsh.JFFSDM
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String jffsdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kh_jsh.JFKH
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String jfkh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kh_jsh.FPDYFS
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String fpdyfs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kh_jsh.FPHQFS
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String fphqfs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kh_jsh.DQYE
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private BigDecimal dqye;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kh_jsh.SDYE
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private BigDecimal sdye;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kh_jsh.YFXE
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private BigDecimal yfxe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kh_jsh.DQBM
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String dqbm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kh_jsh.CJSJ
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private Date cjsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kh_jsh.CZSJ
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private Date czsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kh_jsh
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kh_jsh.JSHH
     *
     * @return the value of kh_jsh.JSHH
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getJshh() {
        return jshh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kh_jsh.JSHH
     *
     * @param jshh the value for kh_jsh.JSHH
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setJshh(String jshh) {
        this.jshh = jshh == null ? null : jshh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kh_jsh.GDDWBM
     *
     * @return the value of kh_jsh.GDDWBM
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getGddwbm() {
        return gddwbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kh_jsh.GDDWBM
     *
     * @param gddwbm the value for kh_jsh.GDDWBM
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setGddwbm(String gddwbm) {
        this.gddwbm = gddwbm == null ? null : gddwbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kh_jsh.KHBH
     *
     * @return the value of kh_jsh.KHBH
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getKhbh() {
        return khbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kh_jsh.KHBH
     *
     * @param khbh the value for kh_jsh.KHBH
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setKhbh(String khbh) {
        this.khbh = khbh == null ? null : khbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kh_jsh.JSHMC
     *
     * @return the value of kh_jsh.JSHMC
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getJshmc() {
        return jshmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kh_jsh.JSHMC
     *
     * @param jshmc the value for kh_jsh.JSHMC
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setJshmc(String jshmc) {
        this.jshmc = jshmc == null ? null : jshmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kh_jsh.JSHDZ
     *
     * @return the value of kh_jsh.JSHDZ
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getJshdz() {
        return jshdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kh_jsh.JSHDZ
     *
     * @param jshdz the value for kh_jsh.JSHDZ
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setJshdz(String jshdz) {
        this.jshdz = jshdz == null ? null : jshdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kh_jsh.JFFSDM
     *
     * @return the value of kh_jsh.JFFSDM
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getJffsdm() {
        return jffsdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kh_jsh.JFFSDM
     *
     * @param jffsdm the value for kh_jsh.JFFSDM
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setJffsdm(String jffsdm) {
        this.jffsdm = jffsdm == null ? null : jffsdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kh_jsh.JFKH
     *
     * @return the value of kh_jsh.JFKH
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getJfkh() {
        return jfkh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kh_jsh.JFKH
     *
     * @param jfkh the value for kh_jsh.JFKH
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setJfkh(String jfkh) {
        this.jfkh = jfkh == null ? null : jfkh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kh_jsh.FPDYFS
     *
     * @return the value of kh_jsh.FPDYFS
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getFpdyfs() {
        return fpdyfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kh_jsh.FPDYFS
     *
     * @param fpdyfs the value for kh_jsh.FPDYFS
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setFpdyfs(String fpdyfs) {
        this.fpdyfs = fpdyfs == null ? null : fpdyfs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kh_jsh.FPHQFS
     *
     * @return the value of kh_jsh.FPHQFS
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getFphqfs() {
        return fphqfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kh_jsh.FPHQFS
     *
     * @param fphqfs the value for kh_jsh.FPHQFS
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setFphqfs(String fphqfs) {
        this.fphqfs = fphqfs == null ? null : fphqfs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kh_jsh.DQYE
     *
     * @return the value of kh_jsh.DQYE
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public BigDecimal getDqye() {
        return dqye;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kh_jsh.DQYE
     *
     * @param dqye the value for kh_jsh.DQYE
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setDqye(BigDecimal dqye) {
        this.dqye = dqye;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kh_jsh.SDYE
     *
     * @return the value of kh_jsh.SDYE
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public BigDecimal getSdye() {
        return sdye;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kh_jsh.SDYE
     *
     * @param sdye the value for kh_jsh.SDYE
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setSdye(BigDecimal sdye) {
        this.sdye = sdye;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kh_jsh.YFXE
     *
     * @return the value of kh_jsh.YFXE
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public BigDecimal getYfxe() {
        return yfxe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kh_jsh.YFXE
     *
     * @param yfxe the value for kh_jsh.YFXE
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setYfxe(BigDecimal yfxe) {
        this.yfxe = yfxe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kh_jsh.DQBM
     *
     * @return the value of kh_jsh.DQBM
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getDqbm() {
        return dqbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kh_jsh.DQBM
     *
     * @param dqbm the value for kh_jsh.DQBM
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setDqbm(String dqbm) {
        this.dqbm = dqbm == null ? null : dqbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kh_jsh.CJSJ
     *
     * @return the value of kh_jsh.CJSJ
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public Date getCjsj() {
        return cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kh_jsh.CJSJ
     *
     * @param cjsj the value for kh_jsh.CJSJ
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setCjsj(Date cjsj) {
        this.cjsj = cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kh_jsh.CZSJ
     *
     * @return the value of kh_jsh.CZSJ
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public Date getCzsj() {
        return czsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kh_jsh.CZSJ
     *
     * @param czsj the value for kh_jsh.CZSJ
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setCzsj(Date czsj) {
        this.czsj = czsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kh_jsh
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", jshh=").append(jshh);
        sb.append(", gddwbm=").append(gddwbm);
        sb.append(", khbh=").append(khbh);
        sb.append(", jshmc=").append(jshmc);
        sb.append(", jshdz=").append(jshdz);
        sb.append(", jffsdm=").append(jffsdm);
        sb.append(", jfkh=").append(jfkh);
        sb.append(", fpdyfs=").append(fpdyfs);
        sb.append(", fphqfs=").append(fphqfs);
        sb.append(", dqye=").append(dqye);
        sb.append(", sdye=").append(sdye);
        sb.append(", yfxe=").append(yfxe);
        sb.append(", dqbm=").append(dqbm);
        sb.append(", cjsj=").append(cjsj);
        sb.append(", czsj=").append(czsj);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}