package com.wjh.entity;

import java.io.Serializable;
import java.util.Date;

public class XtDmxx implements Serializable {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_dmxx.dmbs
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String dmbs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_dmxx.dmmc
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String dmmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_dmxx.dmbh
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String dmbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_dmxx.dmlb
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_dmxx.dmsjdm
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String dmsjdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_dmxx.dmflbm
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String dmflbm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_dmxx.dmflmc
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_dmxx.cjrbs
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String cjrbs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_dmxx.czrbs
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String czrbs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_dmxx.dmzt
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String dmzt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_dmxx.cjsj
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private Date cjsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_dmxx.czsj
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private Date czsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xt_dmxx
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_dmxx.dmbs
     *
     * @return the value of xt_dmxx.dmbs
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getDmbs() {
        return dmbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_dmxx.dmbs
     *
     * @param dmbs the value for xt_dmxx.dmbs
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setDmbs(String dmbs) {
        this.dmbs = dmbs == null ? null : dmbs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_dmxx.dmmc
     *
     * @return the value of xt_dmxx.dmmc
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getDmmc() {
        return dmmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_dmxx.dmmc
     *
     * @param dmmc the value for xt_dmxx.dmmc
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setDmmc(String dmmc) {
        this.dmmc = dmmc == null ? null : dmmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_dmxx.dmbh
     *
     * @return the value of xt_dmxx.dmbh
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getDmbh() {
        return dmbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_dmxx.dmbh
     *
     * @param dmbh the value for xt_dmxx.dmbh
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setDmbh(String dmbh) {
        this.dmbh = dmbh == null ? null : dmbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_dmxx.dmlb
     *
     * @return the value of xt_dmxx.dmlb
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_dmxx.dmlb
     *
     * @param dmlb the value for xt_dmxx.dmlb
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_dmxx.dmsjdm
     *
     * @return the value of xt_dmxx.dmsjdm
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getDmsjdm() {
        return dmsjdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_dmxx.dmsjdm
     *
     * @param dmsjdm the value for xt_dmxx.dmsjdm
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setDmsjdm(String dmsjdm) {
        this.dmsjdm = dmsjdm == null ? null : dmsjdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_dmxx.dmflbm
     *
     * @return the value of xt_dmxx.dmflbm
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getDmflbm() {
        return dmflbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_dmxx.dmflbm
     *
     * @param dmflbm the value for xt_dmxx.dmflbm
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setDmflbm(String dmflbm) {
        this.dmflbm = dmflbm == null ? null : dmflbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_dmxx.dmflmc
     *
     * @return the value of xt_dmxx.dmflmc
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_dmxx.dmflmc
     *
     * @param dmflmc the value for xt_dmxx.dmflmc
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_dmxx.cjrbs
     *
     * @return the value of xt_dmxx.cjrbs
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getCjrbs() {
        return cjrbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_dmxx.cjrbs
     *
     * @param cjrbs the value for xt_dmxx.cjrbs
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setCjrbs(String cjrbs) {
        this.cjrbs = cjrbs == null ? null : cjrbs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_dmxx.czrbs
     *
     * @return the value of xt_dmxx.czrbs
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getCzrbs() {
        return czrbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_dmxx.czrbs
     *
     * @param czrbs the value for xt_dmxx.czrbs
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setCzrbs(String czrbs) {
        this.czrbs = czrbs == null ? null : czrbs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_dmxx.dmzt
     *
     * @return the value of xt_dmxx.dmzt
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getDmzt() {
        return dmzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_dmxx.dmzt
     *
     * @param dmzt the value for xt_dmxx.dmzt
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setDmzt(String dmzt) {
        this.dmzt = dmzt == null ? null : dmzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_dmxx.cjsj
     *
     * @return the value of xt_dmxx.cjsj
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public Date getCjsj() {
        return cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_dmxx.cjsj
     *
     * @param cjsj the value for xt_dmxx.cjsj
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setCjsj(Date cjsj) {
        this.cjsj = cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_dmxx.czsj
     *
     * @return the value of xt_dmxx.czsj
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public Date getCzsj() {
        return czsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_dmxx.czsj
     *
     * @param czsj the value for xt_dmxx.czsj
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setCzsj(Date czsj) {
        this.czsj = czsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_dmxx
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dmbs=").append(dmbs);
        sb.append(", dmmc=").append(dmmc);
        sb.append(", dmbh=").append(dmbh);
        sb.append(", dmsjdm=").append(dmsjdm);
        sb.append(", dmflbm=").append(dmflbm);
        sb.append(", cjrbs=").append(cjrbs);
        sb.append(", czrbs=").append(czrbs);
        sb.append(", dmzt=").append(dmzt);
        sb.append(", cjsj=").append(cjsj);
        sb.append(", czsj=").append(czsj);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}