package com.wjh.entity;

import java.io.Serializable;
import java.util.Date;


public class XtGlyxx implements Serializable {
    //管理员状态
    private String glyzt;

    public String getGlyzt() {
        return glyzt;
    }

    public void setGlyzt(String glyzt) {
        this.glyzt = glyzt;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_glyxx.GLYBH
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String glybh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_glyxx.ZZBM
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String zzbm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_glyxx.GLYMC
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String glymc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_glyxx.JSBH
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String jsbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_glyxx.GLYZC
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String glyzc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_glyxx.GLYLXFS
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String glylxfs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_glyxx.GLYCSRQ
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private Date glycsrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_glyxx.DLZH
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String dlzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_glyxx.DLMM
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String dlmm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_glyxx.YDLSBCS
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String ydlsbcs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_glyxx.KYDLSBCS
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String kydlsbcs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_glyxx.DLSBSDSJ
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private Long dlsbsdsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_glyxx.CJSJ
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private Date cjsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_glyxx.CJRBH
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String cjrbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_glyxx.CZSJ
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private Date czsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_glyxx.CZRBH
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String czrbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xt_glyxx
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_glyxx.GLYBH
     *
     * @return the value of xt_glyxx.GLYBH
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getGlybh() {
        return glybh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_glyxx.GLYBH
     *
     * @param glybh the value for xt_glyxx.GLYBH
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setGlybh(String glybh) {
        this.glybh = glybh == null ? null : glybh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_glyxx.ZZBM
     *
     * @return the value of xt_glyxx.ZZBM
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getZzbm() {
        return zzbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_glyxx.ZZBM
     *
     * @param zzbm the value for xt_glyxx.ZZBM
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setZzbm(String zzbm) {
        this.zzbm = zzbm == null ? null : zzbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_glyxx.GLYMC
     *
     * @return the value of xt_glyxx.GLYMC
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getGlymc() {
        return glymc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_glyxx.GLYMC
     *
     * @param glymc the value for xt_glyxx.GLYMC
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setGlymc(String glymc) {
        this.glymc = glymc == null ? null : glymc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_glyxx.JSBH
     *
     * @return the value of xt_glyxx.JSBH
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getJsbh() {
        return jsbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_glyxx.JSBH
     *
     * @param jsbh the value for xt_glyxx.JSBH
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setJsbh(String jsbh) {
        this.jsbh = jsbh == null ? null : jsbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_glyxx.GLYZC
     *
     * @return the value of xt_glyxx.GLYZC
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getGlyzc() {
        return glyzc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_glyxx.GLYZC
     *
     * @param glyzc the value for xt_glyxx.GLYZC
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setGlyzc(String glyzc) {
        this.glyzc = glyzc == null ? null : glyzc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_glyxx.GLYLXFS
     *
     * @return the value of xt_glyxx.GLYLXFS
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getGlylxfs() {
        return glylxfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_glyxx.GLYLXFS
     *
     * @param glylxfs the value for xt_glyxx.GLYLXFS
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setGlylxfs(String glylxfs) {
        this.glylxfs = glylxfs == null ? null : glylxfs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_glyxx.GLYCSRQ
     *
     * @return the value of xt_glyxx.GLYCSRQ
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public Date getGlycsrq() {
        return glycsrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_glyxx.GLYCSRQ
     *
     * @param glycsrq the value for xt_glyxx.GLYCSRQ
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setGlycsrq(Date glycsrq) {
        this.glycsrq = glycsrq == null ? null : glycsrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_glyxx.DLZH
     *
     * @return the value of xt_glyxx.DLZH
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getDlzh() {
        return dlzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_glyxx.DLZH
     *
     * @param dlzh the value for xt_glyxx.DLZH
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setDlzh(String dlzh) {
        this.dlzh = dlzh == null ? null : dlzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_glyxx.DLMM
     *
     * @return the value of xt_glyxx.DLMM
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getDlmm() {
        return dlmm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_glyxx.DLMM
     *
     * @param dlmm the value for xt_glyxx.DLMM
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setDlmm(String dlmm) {
        this.dlmm = dlmm == null ? null : dlmm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_glyxx.YDLSBCS
     *
     * @return the value of xt_glyxx.YDLSBCS
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getYdlsbcs() {
        return ydlsbcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_glyxx.YDLSBCS
     *
     * @param ydlsbcs the value for xt_glyxx.YDLSBCS
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setYdlsbcs(String ydlsbcs) {
        this.ydlsbcs = ydlsbcs == null ? null : ydlsbcs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_glyxx.KYDLSBCS
     *
     * @return the value of xt_glyxx.KYDLSBCS
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getKydlsbcs() {
        return kydlsbcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_glyxx.KYDLSBCS
     *
     * @param kydlsbcs the value for xt_glyxx.KYDLSBCS
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setKydlsbcs(String kydlsbcs) {
        this.kydlsbcs = kydlsbcs == null ? null : kydlsbcs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_glyxx.DLSBSDSJ
     *
     * @return the value of xt_glyxx.DLSBSDSJ
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public Long getDlsbsdsj() {
        return dlsbsdsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_glyxx.DLSBSDSJ
     *
     * @param dlsbsdsj the value for xt_glyxx.DLSBSDSJ
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setDlsbsdsj(Long dlsbsdsj) {
        this.dlsbsdsj = dlsbsdsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_glyxx.CJSJ
     *
     * @return the value of xt_glyxx.CJSJ
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public Date getCjsj() {
        return cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_glyxx.CJSJ
     *
     * @param cjsj the value for xt_glyxx.CJSJ
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setCjsj(Date cjsj) {
        this.cjsj = cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_glyxx.CJRBH
     *
     * @return the value of xt_glyxx.CJRBH
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getCjrbh() {
        return cjrbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_glyxx.CJRBH
     *
     * @param cjrbh the value for xt_glyxx.CJRBH
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setCjrbh(String cjrbh) {
        this.cjrbh = cjrbh == null ? null : cjrbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_glyxx.CZSJ
     *
     * @return the value of xt_glyxx.CZSJ
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public Date getCzsj() {
        return czsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_glyxx.CZSJ
     *
     * @param czsj the value for xt_glyxx.CZSJ
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setCzsj(Date czsj) {
        this.czsj = czsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_glyxx.CZRBH
     *
     * @return the value of xt_glyxx.CZRBH
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getCzrbh() {
        return czrbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_glyxx.CZRBH
     *
     * @param czrbh the value for xt_glyxx.CZRBH
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setCzrbh(String czrbh) {
        this.czrbh = czrbh == null ? null : czrbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_glyxx
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", glybh=").append(glybh);
        sb.append(", zzbm=").append(zzbm);
        sb.append(", glymc=").append(glymc);
        sb.append(", jsbh=").append(jsbh);
        sb.append(", glyzc=").append(glyzc);
        sb.append(", glylxfs=").append(glylxfs);
        sb.append(", glycsrq=").append(glycsrq);
        sb.append(", dlzh=").append(dlzh);
        sb.append(", dlmm=").append(dlmm);
        sb.append(", ydlsbcs=").append(ydlsbcs);
        sb.append(", kydlsbcs=").append(kydlsbcs);
        sb.append(", dlsbsdsj=").append(dlsbsdsj);
        sb.append(", cjsj=").append(cjsj);
        sb.append(", cjrbh=").append(cjrbh);
        sb.append(", czsj=").append(czsj);
        sb.append(", czrbh=").append(czrbh);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}