package com.wjh.entity;

import org.apache.ibatis.annotations.Mapper;

import java.io.Serializable;
import java.util.Date;

public class XtGnxx implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_gnxx.gnbh
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */




    private String gnbh;

    private String zjljdz;

    public String getZjljdz() {
        return zjljdz;
    }

    public void setZjljdz(String zjljdz) {
        this.zjljdz = zjljdz;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_gnxx.sjgnbh
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String sjgnbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_gnxx.gnmc
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String gnmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_gnxx.gnljdz
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String gnljdz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_gnxx.gnlbdm
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String gnlbdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_gnxx.gnbbh
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String gnbbh;

    private String gnicon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_gnxx.cjsj
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private Date cjsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_gnxx.czsj
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private Date czsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xt_gnxx
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_gnxx.gnbh
     *
     * @return the value of xt_gnxx.gnbh
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getGnbh() {
        return gnbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_gnxx.gnbh
     *
     * @param gnbh the value for xt_gnxx.gnbh
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setGnbh(String gnbh) {
        this.gnbh = gnbh == null ? null : gnbh.trim();
    }

    public String getGnicon() {
        return gnicon;
    }

    public void setGnicon(String gnicon) {
        this.gnicon = gnicon;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_gnxx.sjgnbh
     *
     * @return the value of xt_gnxx.sjgnbh
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getSjgnbh() {
        return sjgnbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_gnxx.sjgnbh
     *
     * @param sjgnbh the value for xt_gnxx.sjgnbh
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setSjgnbh(String sjgnbh) {
        this.sjgnbh = sjgnbh == null ? null : sjgnbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_gnxx.gnmc
     *
     * @return the value of xt_gnxx.gnmc
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getGnmc() {
        return gnmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_gnxx.gnmc
     *
     * @param gnmc the value for xt_gnxx.gnmc
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setGnmc(String gnmc) {
        this.gnmc = gnmc == null ? null : gnmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_gnxx.gnljdz
     *
     * @return the value of xt_gnxx.gnljdz
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getGnljdz() {
        return gnljdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_gnxx.gnljdz
     *
     * @param gnljdz the value for xt_gnxx.gnljdz
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setGnljdz(String gnljdz) {
        this.gnljdz = gnljdz == null ? null : gnljdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_gnxx.gnlbdm
     *
     * @return the value of xt_gnxx.gnlbdm
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getGnlbdm() {
        return gnlbdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_gnxx.gnlbdm
     *
     * @param gnlbdm the value for xt_gnxx.gnlbdm
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setGnlbdm(String gnlbdm) {
        this.gnlbdm = gnlbdm == null ? null : gnlbdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_gnxx.gnbbh
     *
     * @return the value of xt_gnxx.gnbbh
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getGnbbh() {
        return gnbbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_gnxx.gnbbh
     *
     * @param gnbbh the value for xt_gnxx.gnbbh
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setGnbbh(String gnbbh) {
        this.gnbbh = gnbbh == null ? null : gnbbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_gnxx.cjsj
     *
     * @return the value of xt_gnxx.cjsj
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public Date getCjsj() {
        return cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_gnxx.cjsj
     *
     * @param cjsj the value for xt_gnxx.cjsj
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setCjsj(Date cjsj) {
        this.cjsj = cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_gnxx.czsj
     *
     * @return the value of xt_gnxx.czsj
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public Date getCzsj() {
        return czsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_gnxx.czsj
     *
     * @param czsj the value for xt_gnxx.czsj
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setCzsj(Date czsj) {
        this.czsj = czsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_gnxx
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", gnbh=").append(gnbh);
        sb.append(", sjgnbh=").append(sjgnbh);
        sb.append(", gnmc=").append(gnmc);
        sb.append(", gnljdz=").append(gnljdz);
        sb.append(", gnlbdm=").append(gnlbdm);
        sb.append(", gnbbh=").append(gnbbh);
        sb.append(", cjsj=").append(cjsj);
        sb.append(", czsj=").append(czsj);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}