package com.wjh.entity;

import java.io.Serializable;
import java.util.Date;

public class XtJsgnxx implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_jsgnxx.glybh
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String glybh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_jsgnxx.gnbh
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String gnbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_jsgnxx.cjrbs
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String cjrbs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_jsgnxx.czrbs
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String czrbs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_jsgnxx.cjsj
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private Date cjsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_jsgnxx.czsj
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private Date czsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xt_jsgnxx
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_jsgnxx.glybh
     *
     * @return the value of xt_jsgnxx.glybh
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getGlybh() {
        return glybh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_jsgnxx.glybh
     *
     * @param glybh the value for xt_jsgnxx.glybh
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setGlybh(String glybh) {
        this.glybh = glybh == null ? null : glybh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_jsgnxx.gnbh
     *
     * @return the value of xt_jsgnxx.gnbh
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getGnbh() {
        return gnbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_jsgnxx.gnbh
     *
     * @param gnbh the value for xt_jsgnxx.gnbh
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setGnbh(String gnbh) {
        this.gnbh = gnbh == null ? null : gnbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_jsgnxx.cjrbs
     *
     * @return the value of xt_jsgnxx.cjrbs
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getCjrbs() {
        return cjrbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_jsgnxx.cjrbs
     *
     * @param cjrbs the value for xt_jsgnxx.cjrbs
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setCjrbs(String cjrbs) {
        this.cjrbs = cjrbs == null ? null : cjrbs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_jsgnxx.czrbs
     *
     * @return the value of xt_jsgnxx.czrbs
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getCzrbs() {
        return czrbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_jsgnxx.czrbs
     *
     * @param czrbs the value for xt_jsgnxx.czrbs
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setCzrbs(String czrbs) {
        this.czrbs = czrbs == null ? null : czrbs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_jsgnxx.cjsj
     *
     * @return the value of xt_jsgnxx.cjsj
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public Date getCjsj() {
        return cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_jsgnxx.cjsj
     *
     * @param cjsj the value for xt_jsgnxx.cjsj
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setCjsj(Date cjsj) {
        this.cjsj = cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_jsgnxx.czsj
     *
     * @return the value of xt_jsgnxx.czsj
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public Date getCzsj() {
        return czsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_jsgnxx.czsj
     *
     * @param czsj the value for xt_jsgnxx.czsj
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setCzsj(Date czsj) {
        this.czsj = czsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_jsgnxx
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", glybh=").append(glybh);
        sb.append(", gnbh=").append(gnbh);
        sb.append(", cjrbs=").append(cjrbs);
        sb.append(", czrbs=").append(czrbs);
        sb.append(", cjsj=").append(cjsj);
        sb.append(", czsj=").append(czsj);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}