package com.wjh.entity;

import java.io.Serializable;
import java.util.Date;

public class XtZzxx implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_zzxx.GSDWBM
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String gsdwbm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_zzxx.GSDWMC
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String gsdwmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_zzxx.GSDWLBDM
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String gsdwlbdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_zzxx.GSDWDZ
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String gsdwdz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_zzxx.GSDWSJBM
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String gsdwsjbm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_zzxx.BGDH
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String bgdh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_zzxx.DQBM
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private String dqbm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_zzxx.CJSJ
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private Date cjsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_zzxx.CZSJ
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private Date czsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xt_zzxx
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_zzxx.GSDWBM
     *
     * @return the value of xt_zzxx.GSDWBM
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getGsdwbm() {
        return gsdwbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_zzxx.GSDWBM
     *
     * @param gsdwbm the value for xt_zzxx.GSDWBM
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setGsdwbm(String gsdwbm) {
        this.gsdwbm = gsdwbm == null ? null : gsdwbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_zzxx.GSDWMC
     *
     * @return the value of xt_zzxx.GSDWMC
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getGsdwmc() {
        return gsdwmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_zzxx.GSDWMC
     *
     * @param gsdwmc the value for xt_zzxx.GSDWMC
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setGsdwmc(String gsdwmc) {
        this.gsdwmc = gsdwmc == null ? null : gsdwmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_zzxx.GSDWLBDM
     *
     * @return the value of xt_zzxx.GSDWLBDM
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getGsdwlbdm() {
        return gsdwlbdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_zzxx.GSDWLBDM
     *
     * @param gsdwlbdm the value for xt_zzxx.GSDWLBDM
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setGsdwlbdm(String gsdwlbdm) {
        this.gsdwlbdm = gsdwlbdm == null ? null : gsdwlbdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_zzxx.GSDWDZ
     *
     * @return the value of xt_zzxx.GSDWDZ
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getGsdwdz() {
        return gsdwdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_zzxx.GSDWDZ
     *
     * @param gsdwdz the value for xt_zzxx.GSDWDZ
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setGsdwdz(String gsdwdz) {
        this.gsdwdz = gsdwdz == null ? null : gsdwdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_zzxx.GSDWSJBM
     *
     * @return the value of xt_zzxx.GSDWSJBM
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getGsdwsjbm() {
        return gsdwsjbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_zzxx.GSDWSJBM
     *
     * @param gsdwsjbm the value for xt_zzxx.GSDWSJBM
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setGsdwsjbm(String gsdwsjbm) {
        this.gsdwsjbm = gsdwsjbm == null ? null : gsdwsjbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_zzxx.BGDH
     *
     * @return the value of xt_zzxx.BGDH
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getBgdh() {
        return bgdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_zzxx.BGDH
     *
     * @param bgdh the value for xt_zzxx.BGDH
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setBgdh(String bgdh) {
        this.bgdh = bgdh == null ? null : bgdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_zzxx.DQBM
     *
     * @return the value of xt_zzxx.DQBM
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public String getDqbm() {
        return dqbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_zzxx.DQBM
     *
     * @param dqbm the value for xt_zzxx.DQBM
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setDqbm(String dqbm) {
        this.dqbm = dqbm == null ? null : dqbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_zzxx.CJSJ
     *
     * @return the value of xt_zzxx.CJSJ
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public Date getCjsj() {
        return cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_zzxx.CJSJ
     *
     * @param cjsj the value for xt_zzxx.CJSJ
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setCjsj(Date cjsj) {
        this.cjsj = cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_zzxx.CZSJ
     *
     * @return the value of xt_zzxx.CZSJ
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public Date getCzsj() {
        return czsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_zzxx.CZSJ
     *
     * @param czsj the value for xt_zzxx.CZSJ
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    public void setCzsj(Date czsj) {
        this.czsj = czsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_zzxx
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", gsdwbm=").append(gsdwbm);
        sb.append(", gsdwmc=").append(gsdwmc);
        sb.append(", gsdwlbdm=").append(gsdwlbdm);
        sb.append(", gsdwdz=").append(gsdwdz);
        sb.append(", gsdwsjbm=").append(gsdwsjbm);
        sb.append(", bgdh=").append(bgdh);
        sb.append(", dqbm=").append(dqbm);
        sb.append(", cjsj=").append(cjsj);
        sb.append(", czsj=").append(czsj);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}