spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/wssc?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: sunday
    driver-class-name: com.mysql.jdbc.Driver
#  datasource:
#    name: wccs #数据库名称
#    url: jdbc:mysql://127.0.0.1/spring_boot_test?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
#    username: root
#    password: sunday
#    driver-class-name: com.mysql.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    #druid相关配置
#    druid:
#      #监控统计拦截的filters
#      filters: stat
#      #基本属性
#      url: jdbc:mysql://127.0.0.1/wccs?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
#      username: root
#      password: sunday
#      driver-class-name: com.mysql.jdbc.Driver
#      #配置初始化大小/最小/最大
#      initial-size: 1
#      min-idle: 1
#      max-active: 20
#      #获取连接等待超时时间
#      max-wait: 60000
#      #间隔多久进行一次检测，检测需要关闭的空闲连接
#      time-between-eviction-runs-millis: 60000
#      #一个连接在池中最小生存的时间
#      min-evictable-idle-time-millis: 300000
#      validation-query: SELECT 'x'
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
#      pool-prepared-statements: false
#      max-pool-prepared-statement-per-connection-size: 20

#指定mybatis映射文件的地址
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wjh.mapper


pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check
  #helperDialect: mysql                           #分页插件方言选择
  #reasonable: true                               #合理化参数，设为true时pageNum<=0 时会查第一页， pageNum>pages（超过总数时），会查询最后一页
  #supportMethodsArguments: true