package com.wjh.mapper;

import com.wjh.entity.KhJld;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface KhJldMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kh_jld
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    int deleteByPrimaryKey(@Param("jldbh") String jldbh, @Param("gsdwbm") String gsdwbm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kh_jld
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    int insert(KhJld record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kh_jld
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    KhJld selectByPrimaryKey(@Param("jldbh") String jldbh, @Param("gsdwbm") String gsdwbm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kh_jld
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    List<KhJld> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kh_jld
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    int updateByPrimaryKey(KhJld record);
}