package com.wjh.mapper;

import com.wjh.entity.KhJsh;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface KhJshMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kh_jsh
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    int deleteByPrimaryKey(@Param("jshh") String jshh, @Param("gddwbm") String gddwbm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kh_jsh
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    int insert(KhJsh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kh_jsh
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    KhJsh selectByPrimaryKey(@Param("jshh") String jshh, @Param("gddwbm") String gddwbm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kh_jsh
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    List<KhJsh> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kh_jsh
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    int updateByPrimaryKey(KhJsh record);
}