package com.wjh.mapper;

import com.wjh.entity.XtDmxx;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

@Mapper
public interface XtDmxxMapper {

    List<XtDmxx> loadXtdmChilds(@Param("dmbs") String dmbs);//根据代码标识去查子节点的

    int delSelectXtdm(@Param("rqList") List<String> rqList);

    List<XtDmxx> selectFatherByData();

    List<XtDmxx> selectXtdmByData(@Param("rqData") Map<String,Object> rqData);

    List<Map<String,Object>> getGroupDmflbm();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_dmxx
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    int deleteByPrimaryKey(String dmbs);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_dmxx
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    int insert(XtDmxx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_dmxx
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    XtDmxx selectByPrimaryKey(String dmbs);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_dmxx
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    List<XtDmxx> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_dmxx
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    int updateByPrimaryKey(XtDmxx record);
}