package com.wjh.mapper;

import com.wjh.entity.XtGlyxx;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface XtGlyxxMapper {
    //根据条件获取系统管理员
    List<XtGlyxx> findXtglyByData(@Param("queryData") Map<String,Object> data);

    //重置密码
    int resetPassword(@Param("rqDataList") List<Map<String,Object>> rqDataList);

    //更新管理员资料
    int updateXtglyData(@Param("rqData") Map<String,Object> rqData);


    //通过登陆账号查找管理员
    XtGlyxx findXtglyById(@Param("dlzh") String dlzh);

    int deleteByPrimaryKey(@Param("glybh") String glybh, @Param("zzbm") String zzbm);

    //删除选中的系统管理员list
    int delByPrimaryKeyList(@Param("rqData") List<Object> rqData);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_glyxx
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    int insert(XtGlyxx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_glyxx
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    XtGlyxx selectByPrimaryKey(@Param("glybh") String glybh, @Param("zzbm") String zzbm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_glyxx
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    List<XtGlyxx> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_glyxx
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    int updateByPrimaryKey(XtGlyxx record);
}