package com.wjh.mapper;

import com.wjh.entity.XtGnxx;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface XtGnxxMapper {

    //查找已经分配的系统功能
    List<XtGnxx> findXtGn(@Param("glybh") String glybh);

    //查找已经分配的系统功能
    List<XtGnxx> findGlyGnByGlybh(@Param("glybh") String glybh);

    //获取导航菜单选项
    List<XtGnxx> findGnxx(@Param("glybh") String glybh);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_gnxx
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    int deleteByPrimaryKey(String gnbh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_gnxx
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    int insert(XtGnxx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_gnxx
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    XtGnxx selectByPrimaryKey(String gnbh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_gnxx
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    List<XtGnxx> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_gnxx
     *
     * @mbg.generated Sat Feb 15 02:02:53 CST 2020
     */
    int updateByPrimaryKey(XtGnxx record);
}